# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 528241abfd3fe604c3f397ea8e2d597c5f123de2cc68bd53f02827090bab385ab9d26c129953fbd14186e8d4234f34c0883169481af825b7bae6852c6156e876
  ENV:
    S3_BUCKET_NAME: 'test-valucon'
    S3_ACCESS_KEY:  'AKIAIJ3BOCHB5TO3FYIQ'
    S3_SECRET_KEY:  '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'

test:
  secret_key_base: 0319c012245d2020cbb6aabccf5a636f3a750599e74cc455cb4e5e994ceebec0ea13c216880745b6c176af34777dc03a01d23bf86365b432ce064786ff3166e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
